include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_collection_literals: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_double_quotes: true

    unnecessary_parenthesis: true
    unnecessary_await_in_return: true

    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_slow_async_io: true
    avoid_relative_lib_imports: true

    always_declare_return_types: true

    unawaited_futures: true

    sort_constructors_first: true
    always_use_package_imports: true
    cancel_subscriptions: true
    require_trailing_commas: true
    close_sinks: true
    package_names: true
    eol_at_end_of_file: true
    file_names: true

    exhaustive_cases: true

